//Automatically generated by campaing-convert.py
var campaignlist = [
 {
  "desc": "Blitzkrieg<br>German Campaign 1938-????<br>You take command from the civil war in Spain, to the \"lightning\" victories of early World War II and beyond.\r\n", 
  "file": "camp1.json", 
  "flag": 7, 
  "prestige": 500, 
  "scenarios": 27, 
  "title": "Blitzkrieg"
 }, 
 {
  "desc": "Defending the Reich<br>German Campaign 1942-????<br>While Germany was on the strategic defensive after the fall of Stalingrad, there were several operational offensives before the Soviet conquest of Berlin.<br>You take control of Axis forces trying to re-open the way to Stalingrad, and try to change history. <br>Can you stop the Allies before they reach Berlin?<br>\r\nWARNING!<br>This is the toughest of the Panzer General 2 campaigns.<br>This campaign is for the General who is willing to risk everything to win.", 
  "file": "camp2.json", 
  "flag": 7, 
  "prestige": 1000, 
  "scenarios": 6, 
  "title": "Defending The Reich"
 }, 
 {
  "desc": "Crusade in the West<br>American Campaign 1943 - 1945<br>After success in North Africa and Sicily, The Americans, along with their British allies, decide to invade the soft underbelly of Europe.  You are to lead your troops in the struggle to free Europe from Axis control.  Anything less than an Axis unconditional surrender is unacceptable.", 
  "file": "camp3.json", 
  "flag": 9, 
  "prestige": 1000, 
  "scenarios": 6, 
  "title": "Crusade In The West"
 }, 
 {
  "desc": "Crusade in the West<br>British Campaign 1943 - 1945<br>The tide has turned.  After a long struggle, the British Empire returns to the Continent.  You now lead British forces into battle with the final goal of unconditional surrender of the Axis powers.", 
  "file": "camp4.json", 
  "flag": 22, 
  "prestige": 1000, 
  "scenarios": 6, 
  "title": "Crusade In The West"
 }, 
 {
  "desc": "Onward to Berlin<br>Soviet Campaign 1942 - 1945<br>The Axis fascists are at Stalingrad.  It is time to show the Party that you are the one to lead Soviet troops to the final victory in Berlin.  ", 
  "file": "camp5.json", 
  "flag": 19, 
  "prestige": 1000, 
  "scenarios": 6, 
  "title": "Onward To Berlin"
 }
]