var unitType = { none:-1, soft:0, hard:1, air:2, sea:3 }; 

var equipment = 
{
1: {
 name: "Panzer III",
 id: 1, 
 type: unitType.hard,
 maxAmmo: 16,
 maxFuel: 60,
 icon: "ger-tank-1.png",
 moveRadius: 3,
 attackRadius:2,
},
2: {
 name: "German Air Fighter",
 id: 2,
 type: unitType.air,
 maxAmmo: 8,
 maxFuel: 60,
 icon:"ger-plane-1.png",
 moveRadius: 6,
 attackRadius:1,
},
3: {
 name: "German Infantry",
 id: 3,
 type: unitType.soft,
 maxAmmo: 16,
 maxFuel: 120,
 icon:"ger-inf-1.png",
 moveRadius: 2,
 attackRadius:1,
},
4: {
 name: "German Artilery",
 id: 4,
 type: unitType.hard,
 maxAmmo: 16,
 maxFuel: 10,
 icon:"ger-artl-1.png",
 moveRadius: 1,
 attackRadius:4,
 },
 5: {
 name: "Matilda",
 id: 1, 
 type: unitType.hard,
 maxAmmo: 16,
 maxFuel: 60,
 icon: "eng-tank-1.png",
 moveRadius: 3,
 attackRadius:2,
},
6: {
 name: "England Air Fighter",
 id: 2,
 type: unitType.air,
 maxAmmo: 8,
 maxFuel: 60,
 icon:"eng-plane-1.png",
 moveRadius: 6,
 attackRadius:1,
},
7: {
 name: "England Infantry",
 id: 3,
 type: unitType.soft,
 maxAmmo: 16,
 maxFuel: 120,
 icon:"eng-inf-1.png",
 moveRadius: 2,
 attackRadius:1,
},
8: {
 name: "England Artilery",
 id: 4,
 type: unitType.hard,
 maxAmmo: 16,
 maxFuel: 10,
 icon:"eng-artl-1.png",
 moveRadius: 1,
 attackRadius:4,
 },
};